[package]
name = "run"
version = "0.1.0"
edition = "2021"

[dependencies]
algo_lib = { path = "../algo_lib" }
rust_competitive_helper_util = { git = "https://github.com/amal064/rust-competitive-helper" }
